package com.example.ccs_test_2.common.constants

object Constants {

    const val BASE_URL = "https://cbr.ru/scripts/"
    const val GET_URL = "XML_dynamic.asp"

    const val BOOKMARK_DATABASE_NAME = "currency_database"
    const val TABLE_NAME = "currency_rate_table"

    const val DEFAULT_VALUE_DATE_RANGE_1 = "01/01/2021"
    const val DEFAULT_VALUE_DATE_RANGE_2 = "01/01/2022"
    const val DEFAULT_VALUE_CURRENCY_CODE = "R01235"
    const val DEFAULT_VALUE_CURRENCY_RATE_NAME = "USD"

    const val CURRENCY_RATE_FULL_INFO_REMOTE_ROOT_NAME = "CurrencyRateFullInfo"
    const val CURRENCY_RATE_FULL_INFO_REMOTE_ATTRIBUTE_NAME_ID = "ID"
    const val CURRENCY_RATE_FULL_INFO_REMOTE_ATTRIBUTE_NAME_DATE_RANGE_1 = "DateRange1"
    const val CURRENCY_RATE_FULL_INFO_REMOTE_ATTRIBUTE_NAME_DATE_RANGE_2 = "DateRange2"
    const val CURRENCY_RATE_FULL_INFO_REMOTE_ATTRIBUTE_NAME_CURRENCY_RATE_NAME = "name"
    const val CURRENCY_RATE_FULL_INFO_REMOTE_ATTRIBUTE_NAME_RECORD_LIST = "recordList"


    const val CURRENCY_RATE_ITEM_REMOTE_ROOT_NAME = "Record"
    const val CURRENCY_RATE_ITEM_REMOTE_ATTRIBUTE_NAME_NOMINAL = "Nominal"
    const val CURRENCY_RATE_ITEM_REMOTE_DEFAULT_VALUE_NOMINAL = 1
    const val CURRENCY_RATE_ITEM_REMOTE_ATTRIBUTE_NAME_CURRENCY_RATE_VALUE = "Value"
    const val CURRENCY_RATE_ITEM_REMOTE_DEFAULT_VALUE_CURRENCY_RATE_VALUE = "0.00"
    const val CURRENCY_RATE_ITEM_REMOTE_ATTRIBUTE_NAME_DATE = "Date"
    const val CURRENCY_RATE_ITEM_REMOTE_DEFAULT_VALUE_DATE = "01/01/2001"
    const val CURRENCY_RATE_ITEM_REMOTE_ATTRIBUTE_NAME_ID = "Id"
    const val CURRENCY_RATE_ITEM_REMOTE_DEFAULT_VALUE_ID = "R01235"

    const val CURRENCY_FILTER_TYPE_ASC = "1..10"
    const val CURRENCY_FILTER_TYPE_DESC = "10..1"

    const val MAIN_API_QUERY_DATE_REQ_1 = "date_req1"
    const val MAIN_API_QUERY_DATE_REQ_2 = "date_req2"
    const val MAIN_API_QUERY_VAL_NM_RQ = "VAL_NM_RQ"

    const val CURRENCY_RATE_ITEM_DB_NAME_DEFAULT_VALUE = ""
}